# This Action uses minimal steps to run in ~5 seconds to rapidly:
# look for typos in the codebase using codespell, and
# lint Python code using ruff and provide intuitive GitHub Annotations to contributors.
# https://github.com/codespell-project/codespell#readme
# https://beta.ruff.rs
name: codespell_and_ruff
on:
  push:
  #  branches: [master]
  pull_request:
    branches: [master]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user codespell[toml] ruff
    - run: codespell --skip="RedditImageScraper/Lib/site-packages,static"  # --ignore-words-list="" 
    - run: ruff --extend-exclude="RedditImageScraper/Lib/site-packages" --format=github --line-length=94 --target-version=py38 .
