# This Action uses minimal steps to run in ~5 seconds to rapidly:
# look for typos in the codebase using codespell, and
# lint Python code using ruff and provide intuitive GitHub Annotations to contributors.
# https://github.com/codespell-project/codespell#readme
# https://beta.ruff.rs
name: codespell_and_ruff
on:
  push:
  #  branches: [master]
  pull_request:
    branches: [master]
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: pip install --user codespell[toml] ruff
    - run: codespell || true  # --ignore-words-list="" --skip="*.css,*.js,*.lock,*.po"
    - run: ruff --format=github --select=E9,F63,F7 --target-version=py37 .
    - run: ruff --format=github --select=E9,F63,F7,F82 --target-version=py37 .
    - run: ruff --format=github --line-length=200 --target-version=py37 .
    - run: ruff --format=github --target-version=py37 .
